-- MySQL Script generated by MySQL Workbench
-- Tue Sep 28 20:03:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
                                             `id` BIGINT NOT NULL AUTO_INCREMENT,
                                             `name` VARCHAR(45) NOT NULL,
                                             `role_id` BIGINT NOT NULL,
                                             `password` VARCHAR(55) NOT NULL,
                                             `email` VARCHAR(55) NOT NULL,
                                             `age` BIGINT NOT NULL,
                                             PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
                                                `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                `name` VARCHAR(45) NOT NULL,
                                                `description` VARCHAR(45) NOT NULL,
                                                `price` DOUBLE NOT NULL,
                                                PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
                                              `id` BIGINT NOT NULL AUTO_INCREMENT,
                                              `user_id` BIGINT NOT NULL,
                                              `date_of_purchase` DATE NOT NULL,
                                              `purchase_price` DOUBLE NOT NULL,
                                              PRIMARY KEY (`id`),
                                              INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
                                              CONSTRAINT `user_id`
                                                  FOREIGN KEY (`user_id`)
                                                      REFERENCES `mydb`.`user` (`id`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
                                             `id` BIGINT NOT NULL AUTO_INCREMENT,
                                             `role_name` VARCHAR(45) NOT NULL,
                                             PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- # -- -----------------------------------------------------
-- # -- Table `mydb`.`user_roles`
-- # -- -----------------------------------------------------
-- # CREATE TABLE IF NOT EXISTS `mydb`.`user_roles` (
-- #                                                    `user_id` INT NOT NULL,
-- #                                                    `role_id` INT NOT NULL,
-- #                                                    INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
-- #                                                    INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
-- #                                                    CONSTRAINT `user_id`
-- #                                                        FOREIGN KEY (`user_id`)
-- #                                                            REFERENCES `mydb`.`user` (`id`)
-- #                                                            ON DELETE NO ACTION
-- #                                                            ON UPDATE NO ACTION,
-- #                                                    CONSTRAINT `role_id`
-- #                                                        FOREIGN KEY (`role_id`)
-- #                                                            REFERENCES `mydb`.`role` (`id`)
-- #                                                            ON DELETE NO ACTION
-- #                                                            ON UPDATE NO ACTION)
-- #     ENGINE = InnoDB;
-- #

-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
                                             `order_id` BIGINT NOT NULL,
                                             `product_id` BIGINT NOT NULL,
                                             `count` INT NOT NULL,
                                             INDEX `order_id_idx` (`product_id` ASC) VISIBLE,
                                             INDEX `product_id_idx` (`order_id` ASC) VISIBLE,
                                             CONSTRAINT `order_id`
                                                 FOREIGN KEY (`product_id`)
                                                     REFERENCES `mydb`.`order` (`id`)
                                                     ON DELETE NO ACTION
                                                     ON UPDATE NO ACTION,
                                             CONSTRAINT `product_id`
                                                 FOREIGN KEY (`order_id`)
                                                     REFERENCES `mydb`.`product` (`id`)
                                                     ON DELETE NO ACTION
                                                     ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
